### ISSUE TITLE
NaN Update

### ISSUE THREAD

**Issue by arb** [lxe/node-objhash#3]
Consider updating to NaN 2.x.x to support Node 4.

For an example of the required changes, check out this [diff](https://github.com/continuationlabs/userinfo/commit/b954acf1c8b38a84d0ee3d5e004b9e1cf17b5b61).

**Comment by lxe** [comment]
Upgrading won't help... NaN changed drastically in version 2. I need to rewrite the binding code (again). What's the point of NaN if it keeps changing as often as the node API?

**Comment by arb** [comment]
Excellent question.

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by kkoopa** [comment]
The point is backwards compatibility.
